name: Build Python Package

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
#      - uses: actions/setup-python@v5
#        with:
#          python-version: "3.x"
      - name: Build release distributions
        run: |
          python3 -m pip install --upgrade build
          python3 -m build --outdir "${{ runner.temp }}/dist"
          python3 -m pip install "${{ runner.temp }}/dist/"*.whl
          whl2pyz --outdir "${{ runner.temp }}/bin" --python "/usr/bin/env python3" --compress "${{ runner.temp }}/dist/"*.whl
      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ${{ runner.temp }}/dist/
      - name: Upload bin artifact
        uses: actions/upload-artifact@v4
        with:
          name: bin
          path: ${{ runner.temp }}/bin/
