name: Build Python Package

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
#      - uses: actions/setup-python@v5
#        with:
#          python-version: "3.x"
      - name: Build release distributions
        run: |
          python3 -m pip install --upgrade build
          python3 -m build
          python3 -m pip install dist/*.whl
          whl2pyz --python "/usr/bin/env python3" --compress dist/*.whl
      - name: Upload dis artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
      - name: Upload bin artifact
        uses: actions/upload-artifact@v4
        with:
          name: bin
          path: bin/
