name: Release Python Package

on:
  push:
    tags:
      - '*'

jobs:
  release-build:
    uses: ./.github/workflows/build.yml
  create-release:
    needs: [release-build]
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/
      - name: Create GitHub release
        run: |
          gh release create "${{ github.ref_name }}" --generate-notes dist/*
